name: codestyle

on:
  push:
    paths:
      - '**.py'

jobs:
  format:
    name: Formatting (with black)
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Cache python environment
        id: cache-env
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-formatting-black-20.8b1
      - name: Install black
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          pip install black==20.8b1
      - name: Black Format Check
        run: |
          black --check .
  flake8_py3:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ 3.5, 3.6, 3.7, 3.8, 3.9 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E501,F841,E203,W503,W504 .